config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  # ログイン画面から送られるメアドやパスワードを使ってログインを実行
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users
  end

  root to: 'oogiri_events#index'
  resources :oogiri_events do
    # 確認画面 /oogiri_events/new/confirm というURLをconfirm_newアクションに対応付ける
    post :confirm, action: :confirm_new, on: :new
    # CSV入力のimportアクションの為のルーティング
    post :import, on: :collection
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
=begin
  全てのActiveRecordモデルに共通の処理を与えるのではなく、特定のカテゴリのActiveRecordモデル群にだけ共通
  の処理を追加する場合、特定のテーブルに紐づかない抽象的なクラスを作って、任意のモデルクラス群に継承する
  ことで実現できる。
  抽象的なクラスを作るには、abstract_class = true を指定する。
  なお、この指定が無いとSTI(Single Table Inheritance：単一テーブル継承)と解釈されてしまう。
=end
  self.abstract_class = true
end

app/models/oogiri_event.rb
class OogiriEvent < ApplicationRecord
  # title属性に値が入っていなければ検証エラー/最大30文字まで
  validates :title, presence: true, length: { maximum: 30 }
  # 自作の検証用メソッドの登録
  validate :validate_title_not_including_comma

  belongs_to :user
  # Active Storageで画像を添付できる様にする
  has_one_attached :image

  # scopeを使ったカスタムのクエリー用メソッドの定義
  scope :recent, -> { order(created_at: :desc) }

  # ransackによる検索機能に利用してよいカラムの範囲を制限する
  # ransackable_attributesは検索対象にすることを許可するカラムを指定。それ以外のカラムは無視される。
  def self.ransackable_attributes(auth_object = nil)
    %w[title created_at]
  end

  # ransackable_associationsは検索条件に絡める関連を指定する。空の配列を返す様にオーバーライドすることで、
  # 検索条件に意図しない関連を除外することができる
  def self.ransackable_associations(auth_object = nil)
    []
  end

  # CSV出力
  def self.csv_attributes
    ["title", "description", "created_at", "updated_at"]
  end

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      csv << csv_attributes
      all.each do |oogiri_event|
        csv << csv_attributes.map{ |attr| oogiri_event.send(attr) }
      end
    end
  end

  # CSV入力
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      oogiri_event = new
      # 以下のsliceはslice("title", "description", "created_at", "updated_at")と同じ意味
      oogiri_event.attributes = row.to_hash.slice(*csv_attributes)
      oogiri_event.save!
    end
  end

  # 自作の検証用メソッドの追加(オブジェクト外部から呼ばれることは想定していない為 private)
  private

  def validate_title_not_including_comma
    errors.add(:title, 'にカンマを含めることはできません') if title&.include?(',')
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :oogiri_events
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  # ユーザー管理機能を管理者以外の利用を禁止するフィルタ
  def require_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/oogiri_events_controller.rb
class OogiriEventsController < ApplicationController
  # フィルタを使って重複(ここではshow, edit, update, destroy)を避ける
  before_action :set_oogirievent, only: [ :show, :edit, :update, :destroy ]

  def index
    # 名称による検索
    @q = current_user.oogiri_events.ransack(params[:q])
    # ページ番号に対応するデータの範囲を検索する(kaminariのpageスコープを使う)、per(30)で30件まで表示
    @oogiri_events = @q.result(distict: true).page(params[:page]).per(30)

    # CSV出力実装部分
    respond_to do |format|
      format.html
      format.csv {
        send_data @oogiri_events.generate_csv, filename: "oogiri_events-#{Time.zone.now.strftime('%Y%m%d%S')}.csv"
      }
    end
  end

  def import
    current_user.oogiri_events.import(params[:file])
    redirect_to oogiri_events_url, notice: "イベントを追加しました"
  end

  def show
  end

  def new
    @oogiri_event = OogiriEvent.new
  end

  def create
    @oogiri_event = current_user.oogiri_events.new(oogiri_event_params)

    # params[:back]で"戻る"という文字列を得て、「戻る」ボタンが押されたら現在の入力内容を保持したまま
    # 新規イベント登録入力フォームを表示する。「登録」ボタンが押されたら受け取ったパラメータを元に登録して
    # 一覧画面に戻る
    if params[:back].present?
      render :new
      return
    end

    if @oogiri_event.save
      # デバッグ用にログ出力させたい場合
      # logger.debug "イベント： #{@oogiri_event.attributes.inspect}"

      # イベント新規登録後にメールを送信する
      OogiriEventMailer.creation_email(@oogiri_event).deliver_now
      # ジョブの呼び出し
      # 日時指定してジョブ実行(例：翌日の正午にジョブ実行する場合)
      # SampleJob.set(wait_until: Date.tomorrow.noon).perform_later
      # 一週間後にジョブ実行 SampleJob.set(wait:1.week).perform_later
      # SampleJob.perform_later
      redirect_to @oogiri_event, notice: "イベント「#{@oogiri_event.title}」を登録しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @oogiri_event.update!(oogiri_event_params)
    redirect_to oogiri_events_url, notice: "イベント「#{@oogiri_event.title}」を更新しました。"
  end

  def destroy
    @oogiri_event.destroy
    # Ajaxリクエストを受け取ってイベントの削除を行う
    # head :no_content
  end

=begin
  # 確認画面を表示するアクション
  def confirm_new
    @oogiri_event = current_user.oogiri_events.new(oogiri_event_params)
    render :new unless @oogiri_event.valid?
  end
=end

  private
  # Strong Parameters(許可するパラメータのキーを指定)
  def oogiri_event_params
    params.require(:oogiri_event).permit(:title, :description, :image)
  end

  def set_oogirievent
    @oogiri_event = current_user.oogiri_events.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # ログインしていなくてもSessionsControllerが利用できるようにしておく
  skip_before_action :login_required

  def new
  end

  def create
    # User.findは例外が発生する為ここでは使用しない
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "ログインしました。"
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: "ログアウトしました。"
  end


  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oogiri_events_helper.rb
module OogiriEventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li = message

= form_with model: [:admin, user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      = f.check_box :admin, class: 'form-check-input'
      | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード再入力'
    = f.password_field :password_confirmation, class: 'form-control'
  .nav.justify-content-end
    = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザーの編集

.nav.justify-content-end
  = link_to 'ユーザー一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 ユーザー一覧

.nav.justify-content-end
  = link_to '新規登録', new_admin_user_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = User.human_attribute_name(:name)
      th = User.human_attribute_name(:email)
      th = User.human_attribute_name(:admin)
      th = User.human_attribute_name(:created_at)
      th = User.human_attribute_name(:updated_at)
      th
  tbody
    - @users.each do |user|
      tr
        td = link_to user.name, [:admin, user]
        td = user.email
        td = user.admin? ? 'あり':'なし'
        td = user.created_at
        td = user.updated_at
        td
           = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
           = link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1 ユーザー登録

.nav.justify-content-end
  = link_to 'ユーザー一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
h1 ユーザーの詳細

.nav.justify-content-end
  = link_to 'ユーザー一覧', admin_users_path, class: 'nav-link'

table.table.table-hover
  tbody
    tr
      th = User.human_attribute_name(:id)
      td = @user.id
    tr
      th = User.human_attribute_name(:name)
      td = @user.name
    tr
      th = User.human_attribute_name(:email)
      td = @user.email
    tr
      th = User.human_attribute_name(:admin)
      td = @user.admin? ? 'あり':'なし'
    tr
      th = User.human_attribute_name(:created_at)
      td = @user.created_at
    tr
      th = User.human_attribute_name(:updated_at)
      td = @user.updated_at

.nav.justify-content-end
  = link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3'
  = link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザー「#{@user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | 大喜利イベント情報館
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    / Reactを導入した開発
    / = javascript_pack_tag 'application'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      navbar-brand 大喜利イベント情報館

      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item = link_to 'イベント一覧', oogiri_events_path, class: 'nav-link'
          / ログインユーザーが管理者権限を持っている場合のみナビゲーションバーにユーザー一覧へのリンクを表示する
          - if current_user.admin?
            li.nav-item = link_to 'ユーザー一覧', admin_users_path, class: 'nav-link'
          li.nav-item = link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item = link_to 'ログイン', login_path, class: 'nav-link'

    .container
      - if flash.notice.present?
        .alert.alert-success = flash.notice

  = yield

app/views/oogiri_events/_form.html.slim
/ errors.present?で検証エラーの有無を調べ、エラーがある時のみエラーメッセージ表示
- if oogiri_event.errors.present?
  ul#error_explanation
    - oogiri_event.errors.full_messages.each do |message|
      li = message

/ イベントの入力フォーム
= form_with model: oogiri_event, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', id: 'oogiri_event_title'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'oogiri_event_description'
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control'
  .nav.justify-content-end
    = f.submit nil, class: 'btn btn-primary'

/ このパーシャルは編集と新規イベント登録で使われる

app/views/oogiri_events/confirm_new.html.slim
h1 登録内容の確認

= form_with model: @oogiri_event, local: true do |f|
  table.table.table-hover
    tbody
      tr
        th = OogiriEvent.human_attribute_name(:title)
        td = @oogiri_event.title
        = f.hidden_field :title
      tr
        th = OogiriEvent.human_attribute_name(:description)
        td = simple_format(@oogiri_event.description)
        = f.hidden_field :description
  .nav.justify-content-end
    = f.submit '戻る', name: 'back', class: 'btn btn-secondary mr-3'
    = f.submit '登録', class: 'btn btn-primary'

app/views/oogiri_events/destroy.js.erb
// レスポンスとして返すjavascriptコード(destroyアクションに対応するテンプレート)
document.querySelector("#oogiri_event_<%= @oogiri_event.id %>").style.display = 'none';

// イベントの削除と同時にメッセージを表示する
var message = document.createElement('p');
message.innerText = 'イベント「<%= @oogiri_event.title %>」を削除しました。残るイベントは<%= OogiriEvent.count %>件です。';
document.querySelector('table').insertAdjacentElement('beforebegin', message);

app/views/oogiri_events/edit.html.slim
h1 イベントの編集

.nav.justify-content-end
  = link_to '大喜利イベント一覧', oogiri_events_path, class: 'nav-link'

= render partial: 'form', locals: { oogiri_event: @oogiri_event }

app/views/oogiri_events/index.html.slim
h1 大喜利イベント一覧

/ 検索機能実装
= search_form_for @q, class: 'mb-5' do |f|
  / タイトルによる検索
  .form-group.row
    = f.label :title_cont, 'イベント名', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :title_cont, class: 'form-control'
  / 登録日時による検索(_gteq という検索マッチャーは「該当項目が入力された値と同じか、それより大きいこと」を条件にした時に使う)
  .form-group.row
    = f.label :created_at_gteq, '登録日時', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :created_at_gteq, class: 'form-control'
  .form-group
    .nav.justify-content-end
      = f.submit class: 'btn btn-outline-primary'



.nav.justify-content-end
  = link_to '新規イベント登録', new_oogiri_event_path, class: 'btn btn-primary'

.mb-3
  / 現在のページ情報、他のページへ移動する為のリンク表示(paginateヘルパー)
  = paginate @oogiri_events
  / 全データ件数情報(page_entries_infoヘルパー)
  = page_entries_info @oogiri_events

table.table.table-hover
  thead.thead-default
    tr
      / 一覧画面にソート機能を実装する
      / 降順ソート sort_link(@q, :title, default_order: :desc)
      / 複合的な条件ソート sort_link(@q, :title, [:title, "created_at desc"])
      th = sort_link(@q, :title)
      th = OogiriEvent.human_attribute_name(:created_at)
      th
  tbody
    - @oogiri_events.each do | oogiri_event |
      / 削除動作をコントローラからjavascriptを返して実行する(Ajax)
      / サーバ側でも削除されたイベントに対応するDOM要素を指定する
      tr id = "oogiri_event_#{oogiri_event.id}"
        td = link_to oogiri_event.title, oogiri_event
        td = oogiri_event.created_at
        td
           = link_to '編集', edit_oogiri_event_path(oogiri_event), class: 'btn btn-primary mr-3'
           / Ajaxで非同期に削除する(remote: true を追加, リンクであるaタグのCSSクラスにdeleteを追加)
           = link_to '削除', oogiri_event, method: :delete, remote: true, data: { confirm: "イベント「#{oogiri_event.title}」を削除します。よろしいですか？" }, class: 'btn btn-danger delete'

= link_to 'CSVファイルをエクスポート', oogiri_events_path(format: :csv), class: 'btn btn-primary mb-3'

= form_tag import_oogiri_events_path, multipart: true, class: 'mb-3' do
  br
  p = "ファイルを選択してからインポートボタンを押して下さい"
  = file_field_tag :file
  = submit_tag "CSVファイルをインポート", class: 'btn btn-primary'

app/views/oogiri_events/new.html.slim
h1 大喜利イベントの新規登録

.nav.justify-content-end
  = link_to '大喜利イベント一覧', oogiri_events_path, class: 'nav-link'

= render partial: 'form', locals: { oogiri_event: @oogiri_event }

app/views/oogiri_events/show.html.slim
h1 大喜利イベントの詳細

.nav.justify-content-end
  = link_to '大喜利イベント一覧', oogiri_events_path, class: 'nav-link'

table.table.table-hover
  tbody
    tr
      th = OogiriEvent.human_attribute_name(:title)
      td = @oogiri_event.title
    tr
      th = OogiriEvent.human_attribute_name(:description)
      / 文字列内の改行を<br>タグなどに変換して安全なHTML形式に変換
      / URLを含む詳しい説明を画面に表示する
      td = auto_link(simple_format(h(@oogiri_event.description), {}, sanitize: false, wrapper_tag: "div"))
    tr
      / @oogiri_event.image.attached?という判定メソッドで実際に画像が添付されている時だけimage_tagで画像を表示
      th = OogiriEvent.human_attribute_name(:image)
      td = image_tag @oogiri_event.image if @oogiri_event.image.attached?
    tr
      th = OogiriEvent.human_attribute_name(:created_at)
      td = @oogiri_event.created_at
    tr
      th = OogiriEvent.human_attribute_name(:updated_at)
      td = @oogiri_event.updated_at
.nav.justify-content-end
  = link_to '編集', edit_oogiri_event_path, class: 'btn btn-primary mr-3'
  = link_to '削除', @oogiri_event, method: :delete, data: { confirm: "イベント「#{@oogiri_event.title}」を削除します。よろしいですか？" }, class: 'btn btn-danger'